blogTitle = "Giacomo Debidda"
subTitle = ""
blogUrl = "http://giacomodebidda.com/"
authorName = "Giacomo Debidda"
authorBio = "Written by <strong>Giacomo Debidda</strong>, an italian who lives in Munich. You should follow him on <a href='https://twitter.com/GiacomoDebidda'>Twitter</a> &amp; <a href='https://github.com/jackaljack'>Github</a>"
linkPrefix = "/gatsby-starter-drunkenblog"
gaCode = "UA-41577057-1"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"